export const demoBooks = [
  {
    id: "demo-atomic-habits",
    title: "Atomic Habits",
    author: "James Clear",
    price: "499",
    image: "https://covers.openlibrary.org/b/isbn/9780735211292-L.jpg",
    rating: 4.9,
    createdAt: new Date("2026-01-08"),
    category: { id: "demo-self-help", name: "Self Help", slug: "self-help", createdAt: new Date() },
  },
  {
    id: "demo-deep-work",
    title: "Deep Work",
    author: "Cal Newport",
    price: "429",
    image: "https://covers.openlibrary.org/b/isbn/9781455586691-L.jpg",
    rating: 4.8,
    createdAt: new Date("2026-01-07"),
    category: { id: "demo-productivity", name: "Productivity", slug: "productivity", createdAt: new Date() },
  },
  {
    id: "demo-psychology-money",
    title: "The Psychology of Money",
    author: "Morgan Housel",
    price: "399",
    image: "https://covers.openlibrary.org/b/isbn/9780857197689-L.jpg",
    rating: 4.7,
    createdAt: new Date("2026-01-06"),
    category: { id: "demo-finance", name: "Finance", slug: "finance", createdAt: new Date() },
  },
  {
    id: "demo-alchemist",
    title: "The Alchemist",
    author: "Paulo Coelho",
    price: "299",
    image: "https://covers.openlibrary.org/b/isbn/9780061122415-L.jpg",
    rating: 4.6,
    createdAt: new Date("2026-01-05"),
    category: { id: "demo-fiction", name: "Fiction", slug: "fiction", createdAt: new Date() },
  },
  {
    id: "demo-zero-to-one",
    title: "Zero to One",
    author: "Peter Thiel",
    price: "459",
    image: "https://covers.openlibrary.org/b/isbn/9780804139298-L.jpg",
    rating: 4.5,
    createdAt: new Date("2026-01-04"),
    category: { id: "demo-business", name: "Business", slug: "business", createdAt: new Date() },
  },
  {
    id: "demo-clean-code",
    title: "Clean Code",
    author: "Robert C. Martin",
    price: "699",
    image: "https://covers.openlibrary.org/b/isbn/9780132350884-L.jpg",
    rating: 4.4,
    createdAt: new Date("2026-01-03"),
    category: { id: "demo-programming", name: "Programming", slug: "programming", createdAt: new Date() },
  },
  {
    id: "demo-sapiens",
    title: "Sapiens",
    author: "Yuval Noah Harari",
    price: "549",
    image: "https://covers.openlibrary.org/b/isbn/9780062316097-L.jpg",
    rating: 4.3,
    createdAt: new Date("2026-01-02"),
    category: { id: "demo-history", name: "History", slug: "history", createdAt: new Date() },
  },
  {
    id: "demo-dune",
    title: "Dune",
    author: "Frank Herbert",
    price: "599",
    image: "https://covers.openlibrary.org/b/isbn/9780441172719-L.jpg",
    rating: 4.2,
    createdAt: new Date("2026-01-01"),
    category: { id: "demo-sci-fi", name: "Sci-Fi", slug: "sci-fi", createdAt: new Date() },
  },
];

export const demoCategories = Array.from(
  new Map(demoBooks.map((book) => [book.category.slug, book.category])).values(),
);
